### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by Luyao1271** [alibaba/termd#19]
本地打包之后，运行arthas时跑不起来，但是从官方仓库拉下来就可以正常跑，是我哪里打包的不对吗，也不像是代码的问题

**Comment by qxo** [comment]
我也发现此问题是在windows下maven打包出来不知为何, arthas运行进直接退出了
但在linux下打包后就可以正常使用

**Comment by hengyunabc** [comment]
去掉加载 terminfo.src 的代码了，应该没这个问题了。
